baseURL = "https://zellij.online/"
languageCode = "en-us"
title = "Zellij.online - Terminal sharing that actually works."
disableKinds = ["taxonomy", "term", "RSS", "robotsTXT"]
enableGitInfo = false

[minify]
  disableHTML = false
  minifyOutput = true

[params]
  description = "Share your terminal sessions online. No setup, no port-forwarding - end to end encrypted."
  tagline_1 = "Zellij.online"
  tagline_2 = "Terminal sharing that actually works."

[build]
  writeStats = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
